### PR TITLE
Replace Grapihql with GraphQL Playground

### PR DESCRIPTION
**Pull request by lqez**
Difference between two solutions: https://github.com/prisma/graphql-playground#how-is-this-different-from-graphiql

But still stuck in `Names` problem. This has an error like below;
```
Uncaught Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "BlocksQuery`1" does not.
```

### CODE REVIEW

**Comment by lqez** [comment]
What will be the next step? Just waiting for fixing `Names` or could you address me the entry point to examine? @dahlia

**Comment by dahlia** [comment]
I'm going to reproduce that error on my laptop.

**Comment by dahlia** [comment]
@lqez I fixed the bug you addressed above in the PR #25, and it's just merged to the master.  Could you rebase this on the current master?

**Comment by lqez** [comment]
Wow, it works like a charm. Thanks!
Screen Shot 2019-07-02 at 6 30 46 PM

**Review by dahlia — APPROVED** [review]

**Review by earlbread — APPROVED** [review]

**Comment by dahlia** [comment]
Thanks for your contribution!

おめでとう！

**Comment by lqez** [comment]
@dahlia Thanks! (I've never seen Evangelion so I can't understand what the attached media means)

**Pull request merged**
