### PR TITLE
Usage of stderr instead of stdout

### LINKED ISSUE #100: Prefer stderr instead stdout
We can use `Console.WriteLine` or `Console.Error.WriteLine` to print message on console. This issue means let's use `Console.Error.WriteLine` to print messages. You can read [this article](https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout).

Reference https://github.com/planetarium/libplanet-explorer/pull/98#discussion_r457895845.

### PR DESCRIPTION
**Pull request by brunocasarotti**
It resolves #100  by using stderr instead of stdout

### CODE REVIEW

**Comment by moreal** [comment]
@brunocasarotti Thanks for your contribution! 🙇 One more, Could you replace all the `Console` with `Console.Error` to resolve the issue? Please see also https://github.com/planetarium/libplanet-explorer/issues/100#issuecomment-706489732 for a more detailed description.

**Comment by brunocasarotti** [comment]
Sure @moreal , I have done it and understood better the situation. The article mentioned helped a lot! I didn't know the `stderr` was also used for diagnostic messages too. I have learned something new today :)

**Review by moreal — APPROVED** [review]
@brunocasarotti LGTM! 🎉 Also, I'm glad that you learned new something from our project 😀.
Now It needs more approves because of the internal pull request review policy. Other reviewers can leave other reviews so I suggest you should watch until merging. Thanks for your contributions again. 🙏

**Review by dahlia — APPROVED** [review]

**Review by longfin — APPROVED** [review]

**Review by limebell — APPROVED** [review]
Good work

**Pull request merged**
